# application.yml
#
#Licensed under the Apache License, Version 2.0 (the "License"),
#see LICENSE for more details: http://www.apache.org/licenses/LICENSE-2.0.
#
#:author:  Zhang Yi <loeyae@gmail.com>
#:date:    2019-5-27 14:09:58
#:ex:
# group name:
#     property: value
#
server:
  port: 8081
debug: false
app:
  id: 10000002
  secret: wFIg86dd6fCMrQawfstSgP1j7tzupDy6
  dest: ${APP_DEST:test}

spring:
  profiles:
    active: local
  application:
    name: andyzh-demo
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-name: elasticsearch-cluster
#      cluster-nodes: 192.168.7.231:9300
  #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
  #thymeleaf end
  devtools:
    restart:
        enabled: true
    add-properties: false

  # DataSource StoreConfig
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVICE_HOST:localhost}:${MYSQL_SERVICE_PORT:3306}/springboot_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:doctrine}
    password: ${MYSQL_PASSWORD:doctrine}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: LcHikariCP
      # 池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 等待来自池的连接的最大毫秒数,小于30秒重置为30秒
      connection-timeout: 30000


  # Redis Config
  redis:
    host: ${REDIS_SERVICE_HOST:localhost}
    port: ${REDIS_SERVICE_PORT_REDIS:6379}
    password: ${REDIS_PSWD:0f87990482b26838c1c2702cb1145007}
    #默认使用db2
    database: ${REDIS_DB_NO:1}
# Mybatis-Plus Config
mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 枚举类扫描
  typeEnumsPackage: com.loeyae.springboot.demo.*.enums

logging:
    level:
      web: WARN
      root: WARN
    path: /var/log
elasticsearch:
  cluster-nodes: 192.168.7.231:9200, 192.168.7.231:9201, 192.168.7.231:9202
management:
  health:
    mail:
      enabled: false
    elasticsearch:
      enabled: false
    db:
      enabled: false